export const ROOM_CODE_LENGTH = 6;
export const ROOM_CODE_ALPHABET = '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
export const MIN_NICKNAME_LENGTH = 1;
export const MAX_NICKNAME_LENGTH = 16;
export const MAX_PLAYERS = 8;
export const MIN_PLAYERS = 2;
